mbl/urls.py
"""mbl URL Configuration"""
from django.urls import include, re_path
from django.contrib import admin

from rest_framework import routers

from browser import views
from browser import rest

router = routers.DefaultRouter()
router.register(r'coursegroups', rest.CourseGroupViewSet)
router.register(r'courses', rest.CourseViewSet)
router.register(r'people', rest.PersonViewSet)
router.register(r'institutions', rest.InstitutionViewSet)
router.register(r'locations', rest.LocationViewSet)


urlpatterns = [
    re_path('', include('social.apps.django_app.urls', namespace='social')),
    re_path(r'^logout/$', views.logout_view, name='logout'),
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^$', views.home, name="home"),
    re_path(r'^bulk/(?P<model>[a-z]+)/$', views.bulk_action, name="bulk-action"),

    re_path(r'^course/(?P<course_id>[0-9]+)/$', views.course, name="course"),
    re_path(r'^course/(?P<course_id>[0-9]+)/delete/$', views.course_delete, name="delete-course"),
    re_path(r'^course/(?P<course_id>[0-9]+)/edit/$', views.edit_course, name="edit-course"),
    re_path(r'^course/(?P<course_id>[0-9]+)/add/$', views.attendee_create, name="add-attendee"),
    re_path(r'^course/$', views.course, name="courses"),
    re_path(r'^course/create/$', views.course_create, name="create-course-nogroup"),
    re_path(r'^person/(?P<person_id>[0-9]+)/$', views.person, name="person"),
    re_path(r'^person/(?P<person_id>[0-9]+)/edit/$', views.handle_person, name="edit-person"),
    re_path(r'^person/(?P<person_id>[0-9]+)/split/$', views.split_person, name="split-person"),
    re_path(r'^person/merge/$', views.merge_people, name="merge-people"),
    re_path(r'^person/$', views.person, name="person_list"),
    re_path(r'^person/add/$', views.handle_person, name="add-person"),
    re_path(r'^person/(?P<person_id>[0-9]+)/investigator/add/$',views.add_investigator_record,name='add-investigator'),
    re_path(r'^person/(?P<person_id>[0-9]+)/investigator/(?P<research_id>[0-9]+)/edit/$',views.edit_investigator_record,name='edit-investigator'),
    re_path(r'^person/(?P<person_id>[0-9]+)/investigator/(?P<research_id>[0-9]+)/delete/$', views.delete_investigator_record, name='delete-investigator'),
    re_path(r'^person/(?P<person_id>[0-9]+)/affiliation/(?P<affiliation_id>[0-9]+)/edit/$', views.edit_affiliation, name='edit-affiliation'),
    re_path(r'^person/(?P<person_id>[0-9]+)/affiliation/(?P<affiliation_id>[0-9]+)/delete/$', views.delete_affiliation_record, name='delete-affiliation'),
    re_path(r'^person/(?P<person_id>[0-9]+)/position(?:/(?P<position_id>[0-9]+))?/$', views.position, name='position'),
    re_path(r'^person/(?P<person_id>[0-9]+)/position/(?P<position_id>[0-9]+)/delete/$', views.delete_position, name='delete-position'),
    re_path(r'^institution/(?P<institution_id>[0-9]+)/$', views.institution, name="institution"),
    re_path(r'^institution/(?P<institution_id>[0-9]+)/edit/$', views.edit_institution, name="edit-institution"),
    re_path(r'^institution/$', views.institution, name="institution_list"),

    re_path(r'^location/(?P<location_id>[0-9]+)/$', views.location, name="location"),
    re_path(r'^location/(?P<location_id>[0-9]+)/edit/$', views.edit_location, name="edit-location"),
    re_path(r'^location/(?P<location_id>[0-9]+)/split/$', views.split_location, name="split-location"),
    re_path(r'^location/$', views.location, name="location_list"),

    re_path(r'^coursegroup/(?P<coursegroup_id>[0-9]+)/$', views.coursegroup, name="coursegroup"),
    re_path(r'^coursegroup/(?P<coursegroup_id>[0-9]+)/edit/$', views.edit_coursegroup, name="edit-coursegroup"),
    re_path(r'^coursegroup/(?P<coursegroup_id>[0-9]+).json$', views.coursegroup_data, name="coursegroup_data"),
    re_path(r'^coursegroup/(?P<coursegroup_id>[0-9]+)/create/$', views.course_create, name="create-course"),
    re_path(r'^coursegroup/$', views.coursegroup, name="coursegroup_list"),
    re_path(r'^about/$', views.about, name="about"),
    re_path(r'^search/$', views.generic_autocomplete, name="search"),

    re_path(r'^rest/', include(router.urls)),
    re_path(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
]

browser/models.py
from django.db import models
from simple_history.models import HistoricalRecords
from django.core.urlresolvers import reverse
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericRelation
from django.contrib.contenttypes.fields import GenericForeignKey

from uuid import uuid4
from django.conf import settings


def generate_uri(model):
    return '/'.join([settings.URI_NAMESPACE, model.__name__.lower(), str(uuid4())])


class URIMixin(models.Model):
    uri = models.CharField(max_length=255, unique=True)

    class Meta:
        abstract = True

    def save(self, *args, **kwargs):
        if not self.uri:
            self.uri = generate_uri(self.__class__)
        super(URIMixin, self).save(*args, **kwargs)


class YearMixin(models.Model):
    year = models.IntegerField()

    class Meta:
        abstract = True


class LastUpdatedMixin(models.Model):
    """
    Model must aleady have an history field.
    """
    class Meta:
        abstract = True

    last_updated = models.DateTimeField(auto_now=True)


class CuratedMixin(models.Model):
    validated = models.BooleanField(default=False, help_text="Indicates that"
                                    " a record has been examined for accuracy."
                                    " This does not necessarily mean that the"
                                    " record has been disambiguated with"
                                    " respect to an authority accord.")
    validated_by = models.ForeignKey('auth.User', null=True, blank=True)
    validated_on = models.DateTimeField(null=True, blank=True)

    split_to = GenericRelation('SplitEvent',
                               content_type_field='original_type',
                               object_id_field='original_instance_id')

    split_from = GenericRelation('SplitEvent',
                                 content_type_field='child_type',
                                 object_id_field='child_instance_id')

    merge_to = GenericRelation('MergeEvent',
                               content_type_field='parent_type',
                               object_id_field='parent_instance_id')

    merge_from = GenericRelation('MergeEvent',
                                 content_type_field='child_type',
                                 object_id_field='child_instance_id')

    class Meta:
        abstract = True


class NameMixin(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        abstract = True

    def __unicode__(self):
        return self.name


class Course(URIMixin, NameMixin, YearMixin, CuratedMixin, LastUpdatedMixin):
    history = HistoricalRecords()
    attendees = models.ManyToManyField('Person', through='Attendance',
                                       related_name='courses')
    is_part_of = models.ManyToManyField('CourseGroup', through='PartOf',
                                        related_name='courses')

    changed_by = models.ForeignKey('auth.User', related_name='edited_courses')

    @property
    def _history_user(self):
        return self.changed_by

    @_history_user.setter
    def _history_user(self, value):
        self.changed_by = value

    @property
    def primary_coursegroup(self):
        return self.is_part_of.all()[0]

    @property
    def number_of_attendees(self):
        return self.attendees.count()

    def get_absolute_url(self):
        return reverse('course', args=[self.id])

    def can_delete(self):
        return self.attendees.count() == 0


class CourseGroup(URIMixin, NameMixin, CuratedMixin, LastUpdatedMixin):
    history = HistoricalRecords()
    changed_by = models.ForeignKey('auth.User', related_name='edited_coursegroups')

    @property
    def _history_user(self):
        return self.changed_by

    @_history_user.setter
    def _history_user(self, value):
        self.changed_by = value

    @property
    def number_of_courses(self):
        return self.courses.count()

    def get_absolute_url(self):
        return reverse('coursegroup', args=[self.id])


class Institution(URIMixin, NameMixin, CuratedMixin, LastUpdatedMixin):
    history = HistoricalRecords()
    authority = models.ForeignKey('KnownInstitution', blank=True, null=True,
                                  help_text="""
    Use this field to specify a known institution (i.e. a location with an entry
    in the Conceptpower name authority).""")

    changed_by = models.ForeignKey('auth.User', related_name='edited_institutions')

    @property
    def _history_user(self):
        return self.changed_by

    @_history_user.setter
    def _history_user(self, value):
        self.changed_by = value

    @property
    def number_of_affiliates(self):
        return self.affiliates.count()

    def get_absolute_url(self):
        return reverse('institution', args=[self.id])


class Location(URIMixin, NameMixin, CuratedMixin, LastUpdatedMixin):
    history = HistoricalRecords()
    authority = models.ForeignKey('KnownLocation', blank=True, null=True,
                                  help_text="""
    Use this field to specify a known location (i.e. a location with an entry
    in the GeoNames database).""")

    changed_by = models.ForeignKey('auth.User', related_name='edited_locations')

    @property
    def _history_user(self):
        return self.changed_by

    @_history_user.setter
    def _history_user(self, value):
        self.changed_by = value

    @property
    def number_of_denizens(self):
        return self.denizens.distinct('pk').count()

    def get_absolute_url(self):
        return reverse('location', args=[self.id])


class Person(URIMixin, CuratedMixin, LastUpdatedMixin):
    history = HistoricalRecords()
    last_name = models.CharField(max_length=255)
    first_name = models.CharField(max_length=255, blank=True)
    affiliations = models.ManyToManyField('Institution', through='Affiliation',
                                          related_name='affiliates')
    locations = models.ManyToManyField('Location', through='Localization',
                                       related_name='denizens')
    authority  = models.ForeignKey('KnownPerson', blank=True, null=True,
                                   help_text="""
    Use this field to specify a known person (i.e. a person with an entry in
    the Conceptpower name authority).""")

    changed_by = models.ForeignKey('auth.User', related_name='edited_persons')

    @property
    def _history_user(self):
        return self.changed_by

    @_history_user.setter
    def _history_user(self, value):
        self.changed_by = value

    @property
    def name(self):
        if hasattr(self, 'first_name'):
            return ' '.join([self.first_name, self.last_name])
        return self.last_name

    @property
    def number_of_courses(self):
        return self.courses.distinct('pk').count()

    @property
    def number_of_affiliations(self):
        return self.affiliations.distinct('pk').count()

    @property
    def number_of_locations(self):
        return self.locations.distinct('pk').count()

    @property
    def is_investigator(self):
        return self.investigator_set.count() > 0

    @property
    def has_position(self):
        return self.position_set.count() > 0

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('person', args=[self.id])


class Affiliation(YearMixin, CuratedMixin, LastUpdatedMixin):
    history = HistoricalRecords()
    person = models.ForeignKey('Person')
    institution = models.ForeignKey('Institution', blank=True, null=True)
    position = models.CharField(max_length=255, blank=True)

    changed_by = models.ForeignKey('auth.User', related_name='edited_affiliations')

    @property
    def _history_user(self):
        return self.changed_by

    @_history_user.setter
    def _history_user(self, value):
        self.changed_by = value

    def __unicode__(self):
        if self.position:
            return u'%s in %i as %s' % (self.institution.name, self.year, self.position)
        return u'%s in %i' % (self.institution.name, self.year)


class Attendance(YearMixin, CuratedMixin, LastUpdatedMixin):
    history = HistoricalRecords()
    person = models.ForeignKey('Person')
    course = models.ForeignKey('Course')

    role = models.CharField(max_length=255, blank=True)

    changed_by = models.ForeignKey('auth.User', related_name='edited_attendances')

    @property
    def _history_user(self):
        return self.changed_by

    @_history_user.setter
    def _history_user(self, value):
        self.changed_by = value

    def __unicode__(self):
        return u'%s as %s' % (self.course.name, self.role)


class PartOf(YearMixin, CuratedMixin, LastUpdatedMixin):
    history = HistoricalRecords()
    course = models.ForeignKey('Course')
    coursegroup = models.ForeignKey('CourseGroup')

    changed_by = models.ForeignKey('auth.User', related_name='edited_part_of')

    @property
    def _history_user(self):
        return self.changed_by

    @_history_user.setter
    def _history_user(self, value):
        self.changed_by = value


class Localization(YearMixin, CuratedMixin, LastUpdatedMixin):
    history = HistoricalRecords()
    person = models.ForeignKey('Person')
    location = models.ForeignKey('Location')

    changed_by = models.ForeignKey('auth.User', related_name='edited_localizations')

    @property
    def _history_user(self):
        return self.changed_by

    @_history_user.setter
    def _history_user(self, value):
        self.changed_by = value

    def __unicode__(self):
        return u'%s in %i' % (self.location.name, self.year)

    @property
    def as_person_locale(self):
        return u'%s in %i' % (self.person.__unicode__(), self.year)


class Investigator(YearMixin, CuratedMixin, LastUpdatedMixin):
    history = HistoricalRecords()
    person = models.ForeignKey('Person')

browser/templates/browser/about.html
{% extends "browser/base.html" %}
{% load app_filters %}
{% load staticfiles %}

{% block main %}
<div class="alert alert-mbl">
    <h1>People</h1>
</div>


<div class="panel panel-mbl">
    <div class="panel-body">
        <div class="media">
            <div class="media-left media-top">
                <a href="https://cbs.asu.edu/kate-maccord">
                    <img class="media-object img-rounded" src="{% static "browser/img/kate.jpg" %}" alt="Kate MacCord">
                </a>
            </div>
            <div class="media-body">
                <a href="https://cbs.asu.edu/kate-maccord"><h4 class="media-heading">Kate MacCord | <span class="text text-danger">Arizona State University</span></h4></a>
                Kate’s research interests lie in using historical and philosophical analyses
                to better understand developmental biology throughout the 20th century (including
                especially the concepts of differentiation and morphogenesis), teeth as a model
                system, and developmental evolution. Her work uses an historical lens to understand
                the practices and epistemology of biological research.
            </div>
        </div>
        <div class="media">
            <div class="media-left media-top">
                <a href="http://orcid.org/0000-0002-1077-1680">
                    <img class="media-object img-rounded" src="{% static "browser/img/john.jpg" %}" alt="John Furfey" width="70">
                </a>
            </div>
            <div class="media-body">
                <a href="http://orcid.org/0000-0002-1077-1680"><h4 class="media-heading">John Furfey | <span class="text text-danger">Marine Biological Laboratory</span></h4></a>
                John Furfey is the contact for questions or issues regarding remote access to electronic
                resources and the content of the MBL Library’s website.  John offers support for citation
                and bibliographic management and operates the systems tracking the research output of the
                Woods Hole scientific community.  John can address questions regarding impact factors and
                altmetrics.  John is the Library liaison to the MBL Bay Paul Center.
            </div>
        </div>
        <div class="media">
            <div class="media-left media-top">
                <a href="https://asu.academia.edu/ErickPeirson">
                    <img class="media-object img-rounded" src="{% static "browser/img/erick.jpg" %}" alt="Erick Peirson" width="70">
                </a>
            </div>
            <div class="media-body">
                <a href="https://asu.academia.edu/ErickPeirson"><h4 class="media-heading">Erick Peirson | <span class="text text-danger">Arizona State University</span></h4></a>
                Erick Peirson is a postdoctoral research associate in the
                <a href="http://devo-evo.lab.asu.edu">Laubichler Lab at ASU</a>, head of research in the
                <a href="http://diging.asu.edu">ASU Digital Innovation Group</a>, and a software developer
                for <a href="http://www.aplacecalledup.com">A Place Called Up Consulting, LLC</a>.
                As a historian, Erick studies the conceptual and epistemological evolution of 20th-century
                ecology, with an emphasis on ecological genetics and British agriculture. As a developer
                and data scientist, he is interested in generating strategies and tools to document and
                analyze historical processes in a computational framework.
            </div>
        </div>
    </div>
</div>

{% endblock %}

browser/templates/browser/affiliation_edit.html
{% extends "browser/change_base.html" %}
{% load addcss %}

{% block title %}Edit Affiliation: {{ person.name }} (Person){% endblock %}
{% block main %}

<div class="alert alert-mbl">
    Person
    <div>
        <span class="h1">{{ person.name }}</span>

    </div>
    {% if person.authority %}
    <div class="text-warning">
        <span class="glyphicon glyphicon-barcode"></span>
        {{ person.authority.conceptpower_uri|urlize }}
    </div>
    {% endif %}
    {% if person.validated %}
    <div>
        <span class="glyphicon glyphicon-ok" style="color:green;"></span>&nbsp;
        Validated by {{ person.validated_by }} on {{ person.validated_on }}.
    </div>
    {% endif %}
</div>

<div class="container">
    <p class="text-info">
        The below form will edit this <strong>Affiliation</strong> record for <strong>{{ person.name }}</strong>.
    </p>

    <form action="." method="post" id="EditAffiliationForm">
    {% csrf_token %}
    {% block form_fields %}
    {% with form.position as field %}
    <div class="row">
        <div class="col-xs-6">
        <div class="form-group">
            {% for error in field.errors %}
            <div class="alert alert-warning">{{ error }}</div>
            {% endfor %}
            <label>{{ field.label }}</label>
            {{ field|addcss:"form-control input-sm" }}
            <p class="text-muted">{{ field.help_text }}</p>
        </div>
        </div>

    {% endwith %}

    {% with form.institution as field %}
        <div class="col-xs-6">
        <div class="form-group">
            {% for error in field.errors %}
            <div class="alert alert-warning">{{ error }}</div>
            {% endfor %}
            <label>{{ field.label }}</label>
            {{ field|addcss:"form-control input-sm" }}
            <div class="list-group" id="institution-results-container"></div>
            <p class="text-muted">{{ field.help_text }}</p>
            {% if messages %}
                <div class="alert alert-danger">
                {% for message in messages %}
                    {{message}}
                {% endfor %}
                </div>
            {% endif %}
            <label class="control-label">{{ form.create_institution.label }} {{ form.create_institution }}</label>
            <span class="text-muted">{{ form.create_institution.help_text }}</span>
        </div>
        </div>
    </div>
    {% endwith %}

    {% with form.institution_id as field %}
        {{ field }}
    {% endwith %}

    {% endblock %}

    <div class="row">
    <div class="text-center">
        <input class="btn btn-success" type="submit" value="Update">
        <a class="btn btn-danger" href="{% url "person" person.id %}">Cancel</a>
    </div>
    </div>

    </form>

<script>
var institution_search = $('#id_institution');
var institution_container = $('#institution-results-container');
var institution_id = $('#id_institution_id');

$(document).ready(function() {
    $(".dropdown-toggle").dropdown();
    $('[data-toggle="tooltip"]').tooltip();
});
var selectInstitutionResult = function(id, name) {
    institution_container.empty();
    institution_search.val(name);
    institution_id.val(id);
}
var searchPromise = null;
institution_search.on('keyup', function(e) {
    institution_id.val('');
    var query = $(this).val();
    if (query.length == 0){
        institution_container.empty();
    } else {
        if (searchPromise) {
            clearTimeout(searchPromise);
        }
        searchPromise = setTimeout(function() {
            $.ajax("{% url "institution-list" %}?name=" + query, {
                success: function(result) {
                    institution_container.empty();
                    result.results.forEach(function(r) {
                        institution_container.append('<a class="list-group-item search-result" id="' + r.id + '" onclick="selectInstitutionResult(' + r.id + ', \''+ r.name +'\')">' + r.name + '</a>');
                    });
                }
            });
        }, 500);
    }
});
</script>

{% endblock %}

</div>

browser/templates/browser/change_course.html
{% extends "browser/change_base.html" %}
{% load addcss %}

{% block form_fields %}
    {% for error in form.non_field_errors %}
    <div class="alert alert-warning">{{ error }}</div>
    {% endfor %}

    {% with form.name as field %}
    <div class="form-group">
        {% for error in field.errors %}
        <div class="alert alert-warning">{{ error }}</div>
        {% endfor %}
        <label>{{ field.label }}</label>
        {{ field|addcss:"form-control input-sm" }}
        <p class="text-muted">{{ field.help_text }}</p>
    </div>
    {% endwith %}

    {% with form.validated as field %}
    <div class="checkbox">
        {% for error in field.errors %}
        <div class="alert alert-warning">{{ error }}</div>
        {% endfor %}
        <label>
            {{ field }} {{ field.label }}
        </label>
        <p class="text-muted">{{ field.help_text }}</p>
    </div>
    {% endwith %}

{% endblock %}

browser/templates/browser/course_create.html
{% extends "browser/base.html" %}
{% load app_filters %}
{% load addcss %}

{% block title %}Create a new course{% endblock %}

{% block main %}
<div class="alert alert-mbl">
    Course Group: <span class="text-warning">{{ coursegroup.name }}</span>
    <div>
        <span class="h1">Create a new course</span>
        <p class="text-info">
            A course record describes a specific event, such as the Embryology course held in 1974.
            Courses generally belong to a course group; for example, the 1974 Embryology course is part of
            a group (series) that began in the late 19th century. Use this form to create a single
            course record to which you can add attendees.
        </p>
    </div>
</div>

<div class="container">
<!-- Coursegroups -->
    <div class="panel panel-mbl">
        <form class="form" action="." method="POST">
            {% csrf_token %}

            <div class="row">
                <div class="col-xs-3">
                    {% with form.year as field %}
                    <div class="form-group">
                        {% for error in field.errors %}
                        <div class="alert alert-warning">{{ error }}</div>
                        {% endfor %}
                        <label>{{ field.label }}</label>
                        {{ field|addcss:"form-control input-sm" }}
                        <p class="text-muted">{{ field.help_text }}</p>
                    </div>
                    {% endwith %}
                </div>
                <div class="col-xs-9">

                    {% with form.name as field %}
                    <div class="form-group">
                        {% for error in field.errors %}
                        <div class="alert alert-warning">{{ error }}</div>
                        {% endfor %}
                        <label>{{ field.label }}</label>
                        {{ field|addcss:"form-control input-sm" }}
                        <p class="text-muted">{{ field.help_text }}</p>
                    </div>
                    {% endwith %}

                    {% with form.validated as field %}
                    <div class="form-group">
                        {% for error in field.errors %}
                        <div class="alert alert-warning">{{ error }}</div>
                        {% endfor %}
                        <label>{{ field.label }}</label>
                        {{ field|addcss:"form-control input-sm" }}
                        <p class="text-muted">{{ field.help_text }}</p>
                    </div>
                    {% endwith %}
                </div>
            </div>
            <div class="text-right">
                <input type="submit" name="Create" value="Create" class="btn btn-success">
            </div>
        </form>
    </div>
</div>

{% endblock %}

browser/templates/browser/coursegroup_list.html
{% extends "browser/base.html" %}
{% load app_filters %}
{% load addcss %}

{% block title %}Course Groups{% endblock %}

{% block main %}



<form class="form ">
    <div class="row">
        <div class="col-sm-10">
            {% with persons.form.name as field %}
            <div class="form-group">
                <div class="input-group">
                    <input type="text" class="form-control" name="name" id="id_name" autofocus placeholder="Search by name"{% if coursegroups.form.name.value %} value="{{ coursegroups.form.name.value }}{% endif %}">
                    <span class="input-group-btn">
                        <button type="submit" class="btn btn-success"><span class="glyphicon glyphicon-search"></span>&nbsp;</button>
                    </span>
                </div>
            </div>
            {% endwith %}
        </div>
        <div class="col-sm-2">
            <div class="clearfix">
                <div class="btn-group pull-right">
                    <a data-toggle="collapse" class="btn btn-primary btn-sm" data-target="#filters"><span class="glyphicon glyphicon-filter"></span> Advanced</a>
                </div>
            </div>
        </div>
    </div>
    {% if course_groups_filter %}
    <div class="collapse" id="filters">
        <div class="row">
            <div class="col-sm-4">
                {% with course_groups_filter.form.occurred_from as field %}
                <div class="form-group">
                    <label>{{ field.label }}</label>
                    {{ field|addcss:"form-control input-sm" }}
                </div>
                {% endwith %}
            </div>
            <div class="col-sm-4">
                {% with course_groups_filter.form.occurred_through as field %}
                <div class="form-group">
                    <label>{{ field.label }}</label>
                    {{ field|addcss:"form-control input-sm" }}
                </div>
                {% endwith %}
            </div>
            <div class="col-sm-4">
                {% with course_groups_filter.form.o as field %}
                <div class="form-group">
                    <label>{{ field.label }}</label>
                    {{ field|addcss:"form-control input-sm" }}
                </div>
                {% endwith %}
            </div>
        </div>
    </div>
    {% else %}
    <div class="row">
        <div class="col-sm-5">
            <h4>No Data</h4>
        </div>
    </div>
    {% endif %}
</form>
<div class="row">
    <div class="col-xs-6 col-xs-offset-3">
        <span class="step-links">
            <ul class="pager">
                {% if course_groups_paginated.has_previous %}
                    <li><a href="?page=1"><span aria-hidden="true">&larr;</span>  first</a></li>
                    <li><a href="?page={{ course_groups_paginated.previous_page_number }}">previous</a></li>
                {% endif %}
                <span style="margin-left: 1%; margin-right: 1%;" class="current">
                    Page {{ course_groups_paginated.number }} of {{ course_groups_paginated.paginator.num_pages }}
                </span>
                {% if course_groups_paginated.has_next %}
                    <li><a href="?page={{ course_groups_paginated.next_page_number }}">next</a></li>
                    <li><a href="?page={{ course_groups_paginated.paginator.num_pages }}">last<span aria-hidden="true">&rarr;</span></a></li>
                {% endif %}
            </ul>
        </span>
    </div>
</div>

<div class="panel panel-mbl">
    <table class="table">
        <thead>
            <tr>

                <th>Name</th>
                <th>Courses</th>
                <th>Years</th>
                <th></th>
            </tr>
        </thead>
        <tbody>

        {% for coursegroup in course_groups_paginated %}
            <tr>

                <td><a href="{% url "coursegroup" coursegroup.id %}">{{ coursegroup.name }}</a></td>
                <td>{{ coursegroup|get_partof_set|length }}</td>
                <td>{{ coursegroup|get_years }}</td>
                <td>
                    {% if coursegroup.validated %}
                    <i class="glyphicon glyphicon-ok-sign" aria-hidden="true"
                        style="color: green;"
                        data-toggle="tooltip"
                        data-title="This record was validated by {{ coursegroup.validated_by }} on {{ coursegroup.validated_on }}">
                    </i>
                    {% else %}
                    <i class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"
                        data-toggle="tooltip"
                        data-title="This record has not yet been validated">
                    </i>
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <div class="row">
        <div class="col-xs-6 col-xs-offset-3">
            <span class="step-links">
                <ul class="pager">
                    {% if course_groups_paginated.has_previous %}
                        <li><a href="?page=1"><span aria-hidden="true">&larr;</span>  first</a></li>
                        <li><a href="?page={{ course_groups_paginated.previous_page_number }}">previous</a></li>
                    {% endif %}
                    <span style="margin-left: 1%; margin-right: 1%;" class="current">
                        Page {{ course_groups_paginated.number }} of {{ course_groups_paginated.paginator.num_pages }}
                    </span>
                    {% if course_groups_paginated.has_next %}
                        <li><a href="?page={{ course_groups_paginated.next_page_number }}">next</a></li>
                        <li><a href="?page={{ course_groups_paginated.paginator.num_pages }}">last<span aria-hidden="true">&rarr;</span></a></li>
                    {% endif %}
                </ul>
            </span>
        </div>
    </div>
</div>

<script>
$('[data-toggle="tooltip"]').tooltip();
</script>
{% endblock %}